language: node_js
node_js:
- 4.3.2
deploy:
  provider: npm
  api_key:
    email: tareqzubidee@gmail.com
    secure: ET8PGs1DO07ei5obKIbMeYxPCAuO5LNy2RPisduUQlf1gQYxnEE7EclGM7TkaE+tUUs/Acz5OtXNDNbIXHOMlm3Z4V+f7riQp0tj/YcEsrYe9EGQn/21wwqavDjXRMNuLmpTuPzwcr0Hj31sy6+YNHI16j0yyEwp7CcEcP25+5RpFOIO+ccHoyzQuYrd07U68uviMx9qjlbLCcdWyVoOkr8H3OeXjif3aU8PzemUf8ZoSjeSGiVKijh9BZTgFAYB5KlGNHCgtvAdG5hMp/bTrknfXKwjcmGeDFmZNS1PwA5k53R+aCMmavLVap7wDcBEHk6P4OcOFyrWp1PCMR22KCiRNxBZBZhZVky1PX18L4Hw3QXVX+liEaCXiNpwOrELrFBw4GLX2yTGi0ckhWxwCkBEJ8XaRc1PXwmKyIblK9WZIr47WPpl3DMQbJzHI1PSsJvGtH1bwgEtWiAy5FjTVZNPeKdI0g9SmDtBs9kCPjV3zfGjt5hXMuEs4lscN5ogZ2rSxSfQ9+XqmOy8ddoz68TUKlC8o5tyifWwRbeicRtB8sgW9eF67E7YrV8weGQeDPkZs5Fx8fCm5pcQW+Bi0CxcxDZM447YRqJZuqavVl03HrCNfj9TQdDDdzXeEshDmA3FWOFM4xLkX+gXvaYsV/NpdcFSa08PPxiWBcDcsnY=
